name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker stop flask-app || true
          docker rm flask-app || true
          docker rmi flask-app || true
          cd flask-cicd-demo || git clone https://github.com/YOUR_USERNAME/YOUR_REPO_NAME.git
          cd YOUR_REPO_NAME
          docker build -t flask-app .
          docker run -d -p 80:80 --name flask-app flask-app