- name: Deploy to EC2
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ubuntu
    key: ${{ secrets.EC2_KEY }}
    port: 22
    script: |
      docker stop flask-app || true
      docker rm flask-app || true
      docker rmi flask-app || true

      if [ ! -d flask-Project ]; then
        git clone https://github.com/mohsin786-sudo/flask-Project.git
      fi
      cd flask-Project

      docker build -t flask-app .
      docker run -d -p 80:80 --name flask-app flask-app
