script: |
  docker stop flask-app || true
  docker rm flask-app || true
  docker rmi flask-app || true
  if [ ! -d flask-cicd-demo ]; then
    git clone https://github.com/REAL_USERNAME/REAL_REPO_NAME.git flask-cicd-demo
  fi
  cd flask-cicd-demo
  docker build -t flask-app .
  docker run -d -p 80:80 --name flask-app flask-app
