name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          # Stop and remove existing container if running
          docker stop flask-app || true
          docker rm flask-app || true
          docker rmi flask-app || true

          # Remove previous project folder if exists
          rm -rf flask-Project

          # Clone the latest code from GitHub
          git clone https://github.com/mohsin786-sudo/flask-Project.git

          # Move into the project directory
          cd flask-Project

          # Build Docker image
          docker build -t flask-app .

          # Run Docker container
          docker run -d -p 80:80 --name flask-app flask-app
